// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwaptvFYPMUsj2xAkE14qPiZO9DYkhGW0',
    appId: '1:423237369638:web:06858fd699087669244be7',
    messagingSenderId: '423237369638',
    projectId: 'flutter-samples-app',
    authDomain: 'flutter-samples-app.firebaseapp.com',
    storageBucket: 'flutter-samples-app.appspot.com',
    measurementId: 'G-N3C9T5P3LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvN7ulepUXKZJ3Zx7xZZtG_Rz7hdxZvzY',
    appId: '1:423237369638:android:1d7a851839b0d3f8244be7',
    messagingSenderId: '423237369638',
    projectId: 'flutter-samples-app',
    storageBucket: 'flutter-samples-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsn8EPCPBEgNMeNsMUdDfX1juJ0TBLuP8',
    appId: '1:423237369638:ios:bb265f6328253c9e244be7',
    messagingSenderId: '423237369638',
    projectId: 'flutter-samples-app',
    storageBucket: 'flutter-samples-app.appspot.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsn8EPCPBEgNMeNsMUdDfX1juJ0TBLuP8',
    appId: '1:423237369638:ios:d3c1987b41eba6af244be7',
    messagingSenderId: '423237369638',
    projectId: 'flutter-samples-app',
    storageBucket: 'flutter-samples-app.appspot.com',
    iosBundleId: 'com.example.firebaseSample.RunnerTests',
  );
}
